#!/bin/bash

# Some lyrics had a loose number or two at the end
# this script removes it, if it exists

fd . "$HOME/.lyrics"  -0 | while read -r -d $'\0' file
do
	tail -n 1 "$file" | grep -E "[0-9]$" && echo "$file"
done
