#!/bin/sh

# Prints all batteries, their percentage remaining and an emoji corresponding
# to charge status (🔌 for plugged up, 🔋 for discharging on battery, etc.).

case $BLOCK_BUTTON in
    3) notify-send "🔋 Battery module" "🔋: discharging
🛑: not charging
🔌: charging
⚡: charged
❗: battery very low!" ;;
esac

# Loop through all attached batteries.
for battery in /sys/class/power_supply/BAT?
do
	# Get its remaining capacity and charge status.
	capacity=$(cat "$battery"/capacity) || break

	status=$(sed "s/Discharging/🔋/;s/Not charging/🛑/;s/Charging/🔌/;s/Full/⚡/" "$battery"/status)

	time=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep "time" | awk {'print $4$5'} | sed "s/hours/ h/;s/minutes/ m/")
	[ "$time" ] && time=$(echo "($time)")

	[ $(echo $status | grep Unknown) ] && [ "$capacity" -ge 95 ] && capacity=100 && status="⚡"

	# If it is discharging and 25% or less, we will add a ❗ as a warning.
	[ "$capacity" -le 25 ] && [ "$status" = "🔋" ] && warn="❗"

	printf "%s%s%s%% %s\n" "$status" "$warn" "$capacity" "$time"
	unset warn
done
