#!/bin/sh

[ "$(mpc status | grep Updating)" ] && echo "updating..." && exit 0

track=$(mpc current | sed 's/&/&amp;/')

color="white"
[ "$(mpc status | grep paused)" ] && color="grey"

time="$(mpc status | sed -n '2p' | awk '{print $3}')"

echo "<span color='$color'>$track $time</span>"
