#!/bin/sh

[ "$(mpc status | grep Updating)" ] && echo "updating..." && exit 0

track=$(mpc current | sed 's/&/&amp;/')

color="white"
[ "$(mpc status | grep paused)" ] && color="grey"

[ "$track" ] && time="$(mpc status '%currenttime%/%totaltime%')"

echo "<span color='$color'>$track $time</span>"
