#!/bin/bash

[ -z "$1" ] && echo "No file given. Exiting..." && exit 1

file="$1"
ext="${file##*.}"

[ "$ext" !=  "png" ] && file="$(mktemp).png" && convert "$1" "$file"

xclip -selection clipboard -t image/png -i "$file" && notify-send "Copied image to clipboard." && exit 0
