#!/bin/bash

currentFile=$(mpc current -f "%file%")
homePlaylistFile="$HOME/.config/mpd/playlists/liked_songs.m3u"

[ "$(grep -F "$currentFile" "$homePlaylistFile")" ] && notify-send "Song already in loved." && exit

[ -z "$(grep -F "$currentFile" "$homePlaylistFile")" ] &&
homeFile="$HOME/Music/$currentFile" && addtoplaylists "$homeFile" &&
love_track "$homeFile" &&
notify-send --icon="$(displayalbumart)" "Added \"$(mpc current)\" to loved."
