#!/bin/bash

LASTFM_API_KEY=069b66ee4d6a7f5e860db3af52c19ab0

tmpFile=$(mktemp)

artist=$(mpc current -f "%artist%\t%title%" | cut  -f 1)
track=$(mpc current -f "%artist%\t%title%" | cut -f 2)

wget -q "https://ws.audioscrobbler.com/2.0/?method=track.getinfo&api_key=$LASTFM_API_KEY&artist=$artist&track=$track&format=json" -O "$tmpFile"

firefox $(jq -r '.track.url' "$tmpFile")

rm "$tmpFile"
