#!/bin/bash

sed 's:/home/vojislav:/home/vojislav/media:g' ~/.config/mpd/playlists/liked_songs.m3u > /tmp/tmp_playlist.m3u
rsync -auvP $1 --delete /tmp/tmp_playlist.m3u vojislav@lazic.xyz:/var/www/subsonic/playlists/liked_songs.m3u

sed 's:/home/vojislav:/home/pi:g' ~/.config/mpd/playlists/liked_songs.m3u > /tmp/tmp_playlist.m3u
rsync -auvP $1 --delete /tmp/tmp_playlist.m3u pi@192.168.0.16:/home/pi/.config/mpd/playlists/liked_songs.m3u
