#!/bin/bash

sleep 1 && \
	gnome-screenshot "$1" -f ~/Pictures/screenshots/"$(date +"%Y-%m-%d-%H%M%S").png" && \
	xclip -selection clipboard -t image/png -i "$(find $HOME/Pictures/screenshots -type f -printf "%T@ %p\n" | sort -n | tail -n 1 | cut -f 2 -d ' ')"
