#!/bin/bash

function wholescreen {
	MONITORS=$(xrandr | grep -o '[0-9]*x[0-9]*[+-][0-9]*[+-][0-9]*')
	# Get the location of the mouse
	XMOUSE=$(xdotool getmouselocation | awk -F "[: ]" '{print $2}')
	YMOUSE=$(xdotool getmouselocation | awk -F "[: ]" '{print $4}')

	for mon in ${MONITORS}; do
	  MONW=$(echo ${mon} | awk -F "[x+]" '{print $1}')
	  MONH=$(echo ${mon} | awk -F "[x+]" '{print $2}')
	  MONX=$(echo ${mon} | awk -F "[x+]" '{print $3}')
	  MONY=$(echo ${mon} | awk -F "[x+]" '{print $4}')
	  (( ${XMOUSE} >= ${MONX} )) && (( ${XMOUSE} <= ${MONX}+${MONW} )) &&
	  (( ${YMOUSE} >= ${MONY} )) && (( ${YMOUSE} <= ${MONY}+${MONH} )) &&
			  maim -g "${MONW}x${MONH}+${MONX}+${MONY}" |
			  tee "$HOME/Pictures/screenshots/$(date +"%Y-%m-%d-%H%M%S").png" |
			  xclip -selection clipboard -t image/png && notify-send "Screenshot taken"
	done
}

function area {
	tmpFile=$(mktemp)
	maim -s > "$tmpFile"
	echo "$tmpFile"
	[ -s "$tmpFile" ] && cat "$tmpFile" | tee "$HOME/Pictures/screenshots/$(date +"%Y-%m-%d-%H%M%S").png" |
	xclip -selection clipboard -t image/png && notify-send "Screenshot taken" && rm "$tmpFile"
}

case "$1" in
	-a) area ;;
	*) wholescreen ;;
esac
