#!/bin/bash

tmpFile=$(mktemp)

file="$1"
artist="$2"
albumArtist="$3"
album="$4"
year="$5"

echo -e "
Artist\t$artist
Album Artist\t$albumArtist
Album\t$album
Year\t$year\n" > "$tmpFile"

vim "$tmpFile"

artist=$(grep -P "^Artist\t" "$tmpFile" | cut -f 2)
albumArtist=$(grep -P "^Album Artist\t" "$tmpFile" | cut -f 2)
album=$(grep -P "^Album\t" "$tmpFile" | cut -f 2)
year=$(grep -P "^Year\t" "$tmpFile" | cut -f 2)

echo "Adding tags..." && eyeD3 -Q -a "$artist" -b "$albumArtist" --release-date="$year" --recording-date="$year" "$file"
