#!/bin/bash
# Toggle touchpad. Requires xf86-input-synaptics.
(xinput --list "SynPS/2 Synaptics TouchPad" | grep "disabled" && xinput set-prop "SynPS/2 Synaptics TouchPad" "Device Enabled" 1)>/dev/null && notify-send "Touchpad reactivated." && exit
xinput set-prop "SynPS/2 Synaptics TouchPad" "Device Enabled" 0 && notify-send "Touchpad deactivated."
