#!/bin/bash

currentFile=$(mpc current -f "%file%")
lineNumberHome=$(grep -nF "$currentFile" "$HOME/.config/mpd/playlists/liked_songs.m3u" | cut -d: -f1)

[ -z "$lineNumberHome" ] && notify-send "Song not in loved tracks." && exit

[ "$lineNumberHome" ] &&
sed -i "$lineNumberHome d" "$HOME/.config/mpd/playlists/liked_songs.m3u" &&
unlove_track "$HOME/Music/$currentFile" &&
notify-send "Removed \"$(mpc current)\" from loved."
