#!/bin/bash

function filter {
	sed "s/'/’/g"
}

baseDir="$HOME/Documents/liked_tracks"

limit=50

wget --quiet "https://ws.audioscrobbler.com/2.0/?method=user.getlovedtracks&user=vojoh&api_key=069b66ee4d6a7f5e860db3af52c19ab0&limit=${limit}&format=json" -O "$baseDir/likedtracks.json"
jq -r '.[].track[] | [.artist.name, .name] | @tsv' "$baseDir/likedtracks.json" > "$baseDir/likedtracks.csv"

homePlaylistFile="$HOME/.config/mpd/playlists/liked_songs.m3u"
piPlaylistFile="$HOME/Documents/liked_tracks/liked_songs_pi.m3u"

while read -r line; do
	artist=$(cut -f1 <<< "$line")
	track=$(cut -f2 <<< "$line")
	file=$(mpc search artist "$artist" title "$track" | head -1)
	#[ -z "$file" ] && echo "NOT FOUND!: $artist - $track"
	[ "$file" ] && [ -z "$(grep -F "$file" "$homePlaylistFile")" ] && echo "FOUND: $file" && \
		homeFile="$HOME/Music/$file" && piFile="/home/pi/Music/$file" && \
	sed -i "2s|^|$homeFile\n|" "$homePlaylistFile" && \
	sed -i "2s|^|$piFile\n|" "$piPlaylistFile"
done < "$baseDir/likedtracks.csv"
