#!/bin/bash

function filter {
	sed "s/'/’/g"
}

baseDir="$HOME/Documents/liked_tracks"

limit=50

wget --quiet "https://ws.audioscrobbler.com/2.0/?method=user.getlovedtracks&user=vojoh&api_key=069b66ee4d6a7f5e860db3af52c19ab0&limit=${limit}&format=json" -O "$baseDir/likedtracks.json"
jq -r '.[].track[] | [.artist.name, .name] | @tsv' "$baseDir/likedtracks.json" > "$baseDir/likedtracks.csv"

homePlaylistFile="$HOME/.config/mpd/playlists/liked_songs.m3u"
piPlaylistFile="$HOME/Documents/liked_tracks/liked_songs_pi.m3u"

while read -r line; do
	artist=$(cut -f1 <<< "$line")
	track=$(cut -f2 <<< "$line")
	#file=$(mpc search "((artist == \"$artist\") AND (title == \"$track\"))" | head -1)
	file=$(mpc search artist "$artist" title "$track" | head -1)
	#[ -z "$file" ] && echo "NOT FOUND!: $artist - $track"
	[ "$file" ] && [ -z "$(grep -F "$file" "$homePlaylistFile")" ] &&
		homeFile="$HOME/Music/$file" &&
	echo -e "$homeFile\n$(cat $homeplaylistfile)" | sponge $homeplaylistfile && echo "FOUND: $file"
	#sed -i "2s|^|$homeFile\n|" "$homePlaylistFile" && echo "FOUND: $file"
done < "$baseDir/likedtracks.csv"
